package CMTPersistence;
// Generated Apr 1, 2017 1:29:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String surname;
     private Date startDate;
     private Date endDate;
     private float unitCost;
     private float salary;
     private String employeeType;

    public Employees() {
    }

    public Employees(String firstname, String surname, Date startDate, Date endDate, float unitCost, float salary, String employeeType) {
       this.firstname = firstname;
       this.surname = surname;
       this.startDate = startDate;
       this.endDate = endDate;
       this.unitCost = unitCost;
       this.salary = salary;
       this.employeeType = employeeType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public float getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(float unitCost) {
        this.unitCost = unitCost;
    }
    public float getSalary() {
        return this.salary;
    }
    
    public void setSalary(float salary) {
        this.salary = salary;
    }
    public String getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(String employeeType) {
        this.employeeType = employeeType;
    }




}


